### PR TITLE
update basic deployment steps

### PR DESCRIPTION
**Pull request by cjschroder**
16 months of banging away on this and we're still rasslin' basic deployment steps. UAA and SCF deploy successfully. Stratos pods all reach a ready state, but I can't access the Stratos Web UI. I'll work on that separately. I have no idea if applications will successfully deploy, and that is also a separate task.

### CODE REVIEW

**Comment by cjschroder** [comment]
also have no idea about the {SYS_RESOURCES] entries that some say need to be in scf-config-values.yaml. I left them out.

**Comment by btat** [comment]
Does omitting the `SYS_RESOURCE` entries work for your deployments? Troy had asked for #225 because it didn't work without them for him.

:+1: for all the other changes

**Comment by cjschroder** [comment]
> Does omitting the `SYS_RESOURCE` entries work for your deployments? Troy had asked for #225 because it didn't work without them for him.
> 
> +1 for all the other changes

Yes, UAA, SCF, and Stratos pods all reached READY 1/1 -- RUNNING states. I've received  multiple conflicting suggestions for SYS_RESOURCE entries, e.g. they're only for HA deployments, and different ideas which roles should be included.

**Comment by cjschroder** [comment]
I should have noted I tested this on an upgraded CaaSP 3.

**Pull request merged**
