### PR TITLE
First attempt to convert YAML -> DocBook 5

### PR DESCRIPTION
**Pull request by tomschr**
This PR contains the following changes:

* a script `bin/yaml2db.py` which understands the `-h`/`--help` option

Let me know if this is useful for you or not. :wink:

## Requirements

It requires the packages:

* `python3-lxml` (you should have that already when you've installed daps, but just in case...)
* `python3-ruamel.yaml`; this is new. This library is needed to preserve any YAML comment

It does:

* Converts your YAML file into DocBook5 file with an appendix root element
* Each YAML section is converted into a `variablelist`
* It works with the content from https://www.suse.com/releasenotes/x86_64/SUSE-CAP/1/#app.secret-sample

## Examples

```yaml
env:
  # Comment1
  var1: "[]"
  # Comment2
  var2: "true"
```

is converted to the following DocBook5 structure:

```xml
<appendix>
   <title><YAML Configuration/title>
   <variablelist>
      <title>env</title>
      <varlistentry>
         <term><varname>var1</varname> = <literal>[]</literal></term>
         <listitem>
            <para>Comment1</para>
         </listitem>
      </varlistentry>
      <varlistentry>
         <term><varname>var2</varname> = <literal>true</literal></term>
         <listitem>
            <para>Comment2</para>
         </listitem>
      </varlistentry>
   </variablelist>
</appendix>
```

## Examples

The following line creates a DocBook 5 file, but skips the YAML sections `services` and `kube`:

```
./bin/yaml2db.py -o app.secret-sample.xml --rootid app.secret-sample -s services -s kube bin/values.yaml
```

## TODOs

* Nested sections like the following is currently not really covered (yet). What to do with them?

```yaml
# Unit [MiB]
    memory:
      request: 93
      limit: ~
```

### CODE REVIEW

**Comment by cjschroder** [comment]
Hi @tomschr , this is what I tried, using the values.yaml for the UAA namespace, and the results. Not sure what to do--

````
$ ./bin/yaml2db.py -o app.sample.xml --rootid app.sample -s services -s kube bin/values.yaml
Namespace(output='app.sample.xml', rootid='app.sample', skip_section=['services', 'kube'], title='YAML Configuration', yamlfile='bin/values.yaml')
Traceback (most recent call last):
  File "./bin/yaml2db.py", line 236, in <module>
    sys.exit(main())
  File "./bin/yaml2db.py", line 224, in main
    root = convert2db(args)
  File "./bin/yaml2db.py", line 174, in convert2db
    yaml = ruamel.yaml.YAML()
AttributeError: 'module' object has no attribute 'YAML'

**Comment by tomschr** [comment]
> this is what I tried [...]
> AttributeError: 'module' object has no attribute 'YAML'

@cjschroder That looks like you haven't installed the package requirements. :wink: On my openSUSE Leap 15.0 machine, I get:

```
$ rpm -q python3-ruamel.yaml python-lxml
python3-ruamel.yaml-0.15.37-lp150.11.1.x86_64
python3-lxml-4.2.1-lp150.98.2.x86_64
```

Can you confirm you have these packages installed?

**Comment by cjschroder** [comment]
@tomschr 
````
rpm -q python3-ruamel.yaml python-lxml
python3-ruamel.yaml-0.14.9-1.1.x86_64
python-lxml-3.6.1-3.5.x86_64
````
Mine are older than your versions.

**Comment by tomschr** [comment]
@cjschroder Ok, then we skip the RPM packages and try it with a virtual Python environment:

1. Create a virtual Python environment with:

       $ python3 -m venv .env

1. Activate it:

       $ source .env/bin/activate

1. Update pip & setuptools:

       $ pip install -U pip setuptools

1. Install the modules lxml and ruamel.yaml:

       $ pip install lxml ruamel.yaml

1. Run the script and use the `-h` option to see if everything works as expected:

       $ ./bin/yaml2db.py -h

1. Now run the script as above.

1. To deactivate your virtual environment, run `deactivate`.

Done! ;-)

**Comment by cjschroder** [comment]
@tomschr Thanks, using the python3 env works.

The kube: section does not convert, and causes this error: 

````
** Section: kube
  Key: external_ips
Traceback (most recent call last):
  File "./bin/yaml2db.py", line 237, in <module>
    sys.exit(main())
  File "./bin/yaml2db.py", line 225, in main
    root = convert2db(args)
  File "./bin/yaml2db.py", line 206, in convert2db
    com = comments(data[sec].ca.comment)
  File "./bin/yaml2db.py", line 142, in comments
    comnodes = iter(node)
TypeError: 'NoneType' object is not iterable
````

I tried deleting various items in the kube: section to see what would happen. I tried adding some sections after it. The document converts as long as the kube: section is not included. I'm going to keep trying to debug -- any ideas what the problem is?

**Comment by cjschroder** [comment]
aha. @tomschr My values.yaml converts without error (the same file I sent you) when I add a comment to the kube: section, like this:

````
kube:
  # a comment here enables conversion
  external_ips: []
````

**Comment by tomschr** [comment]
@cjschroder Thanks for spotting this problem! I've committed a fix now. In the `comments(node)` function, I've checked if node is None. That should avoid any NoneType exception that you've received.

**Pull request closed without merging**
