### PR TITLE
Fix online-docs build, improve wording a little

### PR DESCRIPTION
**Pull request by sknorr**
This should fix your online-docs woes. I know it's not quite a minimal fix, but scnr.

### CODE REVIEW

**Comment by btat** [comment]
May have missed the `/` before the closing `>` on the links

**Comment by sknorr** [comment]
You're right, that was an embarrassingly broken build "fix"... Fixed for real now.

**Comment by btat** [comment]
:+1: Thanks @sknorr !

**Comment by sknorr** [comment]
Thanks for merging!

**Comment by cjschroder** [comment]
:+1: Thank you @sknorr

**Pull request merged**
