### PR TITLE
Update description of pod life-cycle during deployment

### LINKED ISSUE #748: Update description of pod lifecycle during deployment
See `deployment-pod-status` entity in `xml/repeated-content-decl.ent`

Similar to how in CAP 1.x we describe the process of how not all pods become ready, but instead some will restart and others reach a completed state. For example, in kubecf describe how not all pods will appear immediately, but will be spawned by the `ig-...` pod will spawn other pods

### PR DESCRIPTION
**Pull request by KucharczykL**
Closes #748.

### CODE REVIEW

**Comment by KucharczykL** [comment]
I wasn't sure what amount of detail was desired so it might needs a bit of trimming. I didn't edit the second part of that entity (pods restarting).

**Comment by btat** [comment]
Looks good. I _think_ we can comment out/remove the pod restarts one in a subsequent once we confirm it's no longer needed.

Forgot to include this in the original issue description, but can you update the `scf-deploy-complete` entity as well. It's used to describe how the pods and their status should look when the deployment is successful/complete.

**Comment by KucharczykL** [comment]
I have updated the description to reflect the current result. I am not sure whether I should replace all instances of `scf` with `kubecf`. So far I have only edited the commands and pod names.

**Comment by btat** [comment]
Thanks for updating the other entity as well. I think it's fine if we leave the `scf` to `kubecf` change off this PR. We can make a separate PR to update that in all content.

**Pull request merged**
